version: '3.8'

# DB_HOST=localhost
# DB_USER=api_user
# DB_PASSWORD=user_password
# DB_NAME=number_guessing_game
# PORT=5000
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: number_guessing_game
    ports:
      - '3307:3307'
    volumes:
      - db_data:/var/lib/mysql
      # - ./db_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=number_guessing_game

  frontend:
    build: ./frontend
    ports:
      - '3000:5173'
    depends_on:
      - backend

volumes:
  db_data:
